version: '3.4'

services:
  grpc-server:
    build:
      context: backend/grpc-server
      dockerfile: production.Dockerfile
  http-server:
    build:
      context: backend/http-server
      dockerfile: production.Dockerfile
    ports:
      - '8080:8080'
  web-app:
    build:
      context: frontend/web-app
      dockerfile: production.Dockerfile
    ports:
      - '3000:3000'