# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meter_usage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='meter_usage.proto',
  package='meterusage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11meter_usage.proto\x12\nmeterusage\";\n\x0bReadRequest\x12\x16\n\x0etimestamp_from\x18\x01 \x01(\x03\x12\x14\n\x0ctimestamp_to\x18\x02 \x01(\x03\"-\n\tMeterData\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01\x32L\n\nMeterUsage\x12>\n\x08ReadData\x12\x17.meterusage.ReadRequest\x1a\x15.meterusage.MeterData\"\x00\x30\x01\x62\x06proto3'
)




_READREQUEST = _descriptor.Descriptor(
  name='ReadRequest',
  full_name='meterusage.ReadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_from', full_name='meterusage.ReadRequest.timestamp_from', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp_to', full_name='meterusage.ReadRequest.timestamp_to', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=92,
)


_METERDATA = _descriptor.Descriptor(
  name='MeterData',
  full_name='meterusage.MeterData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='meterusage.MeterData.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='meterusage.MeterData.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['ReadRequest'] = _READREQUEST
DESCRIPTOR.message_types_by_name['MeterData'] = _METERDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadRequest = _reflection.GeneratedProtocolMessageType('ReadRequest', (_message.Message,), {
  'DESCRIPTOR' : _READREQUEST,
  '__module__' : 'meter_usage_pb2'
  # @@protoc_insertion_point(class_scope:meterusage.ReadRequest)
  })
_sym_db.RegisterMessage(ReadRequest)

MeterData = _reflection.GeneratedProtocolMessageType('MeterData', (_message.Message,), {
  'DESCRIPTOR' : _METERDATA,
  '__module__' : 'meter_usage_pb2'
  # @@protoc_insertion_point(class_scope:meterusage.MeterData)
  })
_sym_db.RegisterMessage(MeterData)



_METERUSAGE = _descriptor.ServiceDescriptor(
  name='MeterUsage',
  full_name='meterusage.MeterUsage',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=141,
  serialized_end=217,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadData',
    full_name='meterusage.MeterUsage.ReadData',
    index=0,
    containing_service=None,
    input_type=_READREQUEST,
    output_type=_METERDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERUSAGE)

DESCRIPTOR.services_by_name['MeterUsage'] = _METERUSAGE

# @@protoc_insertion_point(module_scope)
